# Generated by Django 5.1.4 on 2024-12-12 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_rename_visiblename_user_visible_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='visible_name',
            new_name='visibleName',
        ),
    ]
