# Generated by Django 5.1.4 on 2024-12-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_chatroom_avatar_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars/chat/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars/user/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chat',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='chats_with_users', to='messenger.chat'),
        ),
        migrations.AlterField(
            model_name='user',
            name='chatroom',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='chatrooms_with_users', to='messenger.chatroom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='favorite_for_user', to='messenger.favorite'),
        ),
    ]
