# Generated by Django 5.1.4 on 2024-12-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_chatroom_avatar_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='max_participants',
            field=models.PositiveIntegerField(default=8, editable=False),
        ),
    ]
