# Generated by Django 5.1.4 on 2024-12-12 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_alter_chatroom_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chatroom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_to_chatroom', to='messenger.chatroom'),
        ),
        migrations.AddField(
            model_name='message',
            name='favorite',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_to_favorite', to='messenger.favorite'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_to_chat', to='messenger.chat'),
        ),
    ]
