# Generated by Django 5.1.4 on 2024-12-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0007_message_chatroom_message_favorite_alter_message_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='favorite',
        ),
        migrations.AddField(
            model_name='message',
            name='is_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
