# Generated by Django 5.1.4 on 2024-12-13 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_remove_message_chat_remove_message_favorite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='visibleName',
        ),
    ]
